get_project_info_resp = {
   'requester':{
      'requestId':'08822_FS',
      'investigator':'Emily Stockfisch',
      'pi':'Neerav Shukla',
      'projectManager':'N/A',
      'cmoProject':'N/A',
      'pipelinable':False,
      'analysisRequested':True,
      'requestedNumberOfReads':'N/A',
      'tumorCount':2,
      'normalCount':1,
      'numSamples':3
   },
   'statuses':{
      'Under-Review':0,
      'IGO-Complete':0,
      'Passed':2,
      'Failed':0,
      'Resequence-Pool':0,
      'Repool-Sample':0,
      'Recapture-Sample':0,
      'New-Library-Needed':0,
      'Required-Additional-Reads':1
   },
   'recordIds':[
      6305783,
      6306013,
      6306019
   ],
   'grid':{
      'header':[
         'Run',
         'Sample',
         'IGO Id',
         'Genome',
         'Quant-it',
         'Library Quality Control',
         'Starting Amount',
         'Tumor or Normal',
         'Concentr.  (nM)',
         'Final Library Yield (fmol)',
         'Requested Reads (Millions)',
         'Initial Pool',
         'QC Status',
         'Pct. Adapters',
         'Reads Examined',
         'Unpaired Reads',
         'Sum Reads',
         'Unmapped',
         'Pct. Duplic.',
         'Pct. Ribos.',
         'Pct. Coding',
         'Pct. Utr',
         'Pct. Intron.',
         'Pct. Intergenic',
         'Pct. Mrna'
      ],
      'val_types':{
         'Run':'s',
         'Sample':'s',
         'IGO Id':'s',
         'Genome':'s',
         'Quant-it':'.2f',
         'Library Quality Control':'.2f',
         'Starting Amount':'.2f',
         'Tumor or Normal':'s',
         'Concentr.  (nM)':'.2f',
         'Final Library Yield (fmol)':'.2f',
         'Requested Reads (Millions)':'.2f',
         'Initial Pool':'s',
         'QC Status':'.2f',
         'Pct. Adapters':'4f',
         'Reads Examined':'d',
         'Unpaired Reads':'d',
         'Sum Reads':'d',
         'Unmapped':'d',
         'Pct. Duplic.':'.2f',
         'Pct. Ribos.':'.2f',
         'Pct. Coding':'.2f',
         'Pct. Utr':'.2f',
         'Pct. Intron.':'.2f',
         'Pct. Intergenic':'.2f',
         'Pct. Mrna':'.2f',
         'Coverage Target':'d'
      },
      'grid':{
         0:{
            'Run':'DIANA_0146_BHWG2YDSXX',
            'QC Status':'Passed',
            'Sample':'XPRO_0234_T_RNA',
            'QC Record Id':6305783,
            'IGO Id':'08822_FS_2',
            'Genome':'Human',
            'Tumor or Normal':'Tumor',
            'Concentr.  (nM)':61.23,
            'Final Library Yield (fmol)':12.14,
            'Coverage Target':'',
            'Requested Reads (Millions)':60,
            'Pct. Adapters':0.0025,
            'Reads Examined':132092085,
            'Unpaired Reads':558406,
            'Initial Pool':'Pool-08822_FS-08822_FT-C1_1',
            'Unmapped':629228,
            'Pct. Duplic.':44.61,
            'Starting Amount':0.0,
            'Library Quality Control':'12.14 ng/uL',
            'Quant-it':'12.14 ng/uL',
            'Sum Reads':132092085,
            'Pct. Ribos.':3.48,
            'Pct. Coding':11.05,
            'Pct. Utr':9.95,
            'Pct. Intron.':27.34,
            'Pct. Intergenic':49.2,
            'Pct. Mrna':21.0
         },
         1:{
            'Run':'DIANA_0146_BHWG2YDSXX',
            'QC Status':'Required-Additional-Reads',
            'Sample':'XPRO_0234_N',
            'QC Record Id':6306013,
            'IGO Id':'08822_FS_3',
            'Genome':'Human',
            'Tumor or Normal':'Normal',
            'Concentr.  (nM)':44.2,
            'Final Library Yield (fmol)':0.0,
            'Coverage Target':40,
            'Requested Reads (Millions)':600,
            'Pct. Adapters':0.0,
            'Reads Examined':402038409,
            'Unpaired Reads':983377,
            'Initial Pool':'Pool-08822_FP-08822_FQ-08822_FS-08822_FT-08822_FU-A1_1',
            'Unmapped':1052294,
            'Pct. Duplic.':17.48,
            'Starting Amount':500.00000000000006,
            'Library Quality Control':'0.00 0.0',
            'Quant-it':'0.00 NA',
            'Sum Reads':402038409,
            'Pct. Ribos.':0.0,
            'Pct. Coding':0.0,
            'Pct. Utr':0.0,
            'Pct. Intron.':0.0,
            'Pct. Intergenic':0.0,
            'Pct. Mrna':0.0
         },
         2:{
            'Run':'DIANA_0146_BHWG2YDSXX',
            'QC Status':'Passed',
            'Sample':'XPRO_0234_T_DNA',
            'QC Record Id':6306019,
            'IGO Id':'08822_FS_1',
            'Genome':'Human',
            'Tumor or Normal':'Tumor',
            'Concentr.  (nM)':31.89,
            'Final Library Yield (fmol)':0.0,
            'Coverage Target':80,
            'Requested Reads (Millions)':1100,
            'Pct. Adapters':0.0,
            'Reads Examined':1698024694,
            'Unpaired Reads':3379743,
            'Initial Pool':'Pool-08822_FP-08822_FQ-08822_FS-08822_FT-08822_FU-A1_1',
            'Unmapped':4069071,
            'Pct. Duplic.':19.83,
            'Starting Amount':500.00000000000006,
            'Library Quality Control':'0.00 0.0',
            'Quant-it':'0.00 NA',
            'Sum Reads':1698024694,
            'Pct. Ribos.':0.0,
            'Pct. Coding':0.0,
            'Pct. Utr':0.0,
            'Pct. Intron.':0.0,
            'Pct. Intergenic':0.0,
            'Pct. Mrna':0.0
         }
      },
      'style':{
         0:{
            'Run':None,
            'QC Status':None,
            'Sample':None,
            'QC Record Id':None,
            'IGO Id':None,
            'Genome':None,
            'Tumor or Normal':'text-danger',
            'Concentr.  (nM)':None,
            'Final Library Yield (fmol)':None,
            'Coverage Target':None,
            'Requested Reads (Millions)':None,
            'Pct. Adapters':None,
            'Reads Examined':None,
            'Unpaired Reads':None,
            'Initial Pool':None,
            'Unmapped':None,
            'Pct. Duplic.':None,
            'Starting Amount':None,
            'Library Quality Control':None,
            'Quant-it':None,
            'Sum Reads':None,
            'Pct. Ribos.':None,
            'Pct. Coding':None,
            'Pct. Utr':None,
            'Pct. Intron.':None,
            'Pct. Intergenic':None,
            'Pct. Mrna':None
         },
         1:{
            'Run':None,
            'QC Status':None,
            'Sample':None,
            'QC Record Id':None,
            'IGO Id':None,
            'Genome':None,
            'Tumor or Normal':'text-primary',
            'Concentr.  (nM)':None,
            'Final Library Yield (fmol)':None,
            'Coverage Target':None,
            'Requested Reads (Millions)':None,
            'Pct. Adapters':None,
            'Reads Examined':None,
            'Unpaired Reads':None,
            'Initial Pool':None,
            'Unmapped':None,
            'Pct. Duplic.':None,
            'Starting Amount':None,
            'Library Quality Control':None,
            'Quant-it':None,
            'Sum Reads':None,
            'Pct. Ribos.':None,
            'Pct. Coding':None,
            'Pct. Utr':None,
            'Pct. Intron.':None,
            'Pct. Intergenic':None,
            'Pct. Mrna':None
         },
         2:{
            'Run':None,
            'QC Status':None,
            'Sample':None,
            'QC Record Id':None,
            'IGO Id':None,
            'Genome':None,
            'Tumor or Normal':'text-danger',
            'Concentr.  (nM)':None,
            'Final Library Yield (fmol)':None,
            'Coverage Target':None,
            'Requested Reads (Millions)':None,
            'Pct. Adapters':None,
            'Reads Examined':None,
            'Unpaired Reads':None,
            'Initial Pool':None,
            'Unmapped':None,
            'Pct. Duplic.':None,
            'Starting Amount':None,
            'Library Quality Control':None,
            'Quant-it':None,
            'Sum Reads':None,
            'Pct. Ribos.':None,
            'Pct. Coding':None,
            'Pct. Utr':None,
            'Pct. Intron.':None,
            'Pct. Intergenic':None,
            'Pct. Mrna':None
         }
      }
   },
   'chartsLinks':{

   },
   'projectType':{
      'recipe':'RNASeq_RiboDeplete',
      'startable':True,
      'quanted':True,
      'qcControlled':True,
      'table':'rna'
   },
   'columnOrder':[
      'QC Status',
      'Sample',
      'Concentr.  (nM)',
      'Final Library Yield (fmol)',
      'Sum Reads',
      'Reads Examined',
      'Unpaired Reads',
      'Requested Reads (Millions)',
      'Unmapped',
      'Tumor or Normal',
      'Pct. Adapters',
      'Pct. Duplic.',
      'Pct. Ribos.',
      'Pct. Coding',
      'Pct. Utr',
      'Pct. Intron.',
      'Pct. Intergenic',
      'Pct. Mrna'
   ]
}
