get_project_info_resp = {
   "requester":{
      "requestId":"09602_F",
      "investigator":"Yongxing Gong",
      "pi":"Ian Ganly",
      "projectManager":"N/A",
      "cmoProject":"N/A",
      "pipelinable":False,
      "analysisRequested":False,
      "requestedNumberOfReads":"N/A",
      "tumorCount":8,
      "normalCount":4,
      "numSamples":12
   },
   "statuses":{
      "Under-Review":0,
      "IGO-Complete":0,
      "Passed":7,
      "Failed":0,
      "Resequence-Pool":0,
      "Repool-Sample":7,
      "Recapture-Sample":0,
      "New-Library-Needed":0,
      "Required-Additional-Reads":3
   },
   "recordIds":[
      5429279,
      5429281,
      5429313,
      5429363,
      5429379,
      5429381,
      5429403,
      5454412,
      5454456,
      5454474,
      5454512,
      5454522,
      5457745,
      5457785,
      5457805,
      5457841,
      5457849
   ],
   "grid":{
      "header":[
         "Run",
         "Sample",
         "IGO Id",
         "Initial Pool",
         "QC Status",
         "Tumor or Normal",
         "Coverage Target",
         "Requested Reads (Millions)",
         "Sum MTC",
         "Sum Reads",
         "Pct. Duplic.",
         "Pct. Off Bait",
         "Mean Tgt Cvg",
         "Reads Examined",
         "Unmapped",
         "Unpaired Reads",
         "Pct. Adapters",
         "Pct. Zero Cvg",
         "Pct. 10x",
         "Pct. 30x",
         "Pct. 100x",
         "Genome",
         "Quant-it",
         "Library Quality Control",
         "Starting Amount"
      ],
      "val_types":{
         "Run":"s",
         "Sample":"s",
         "IGO Id":"s",
         "Initial Pool":"s",
         "QC Status":".2f",
         "Tumor or Normal":"s",
         "Coverage Target":"d",
         "Requested Reads (Millions)":".2f",
         "Sum MTC":".2f",
         "Sum Reads":"d",
         "Pct. Duplic.":".2f",
         "Pct. Off Bait":".2f",
         "Mean Tgt Cvg":".2f",
         "Reads Examined":"d",
         "Unmapped":"d",
         "Unpaired Reads":"d",
         "Pct. Adapters":"4f",
         "Pct. Zero Cvg":".2f",
         "Pct. 10x":".2f",
         "Pct. 30x":".2f",
         "Pct. 100x":".2f",
         "Genome":"s",
         "Quant-it":".2f",
         "Library Quality Control":".2f",
         "Starting Amount":".2f"
      },
      "grid":{
         0:{
            "Run":"JAX_0327_AH772HBBXY",
            "QC Status":"Passed",
            "Sample":"TC7",
            "QC Record Id":5429279,
            "IGO Id":"09602_F_8",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":39.31,
            "Final Library Yield (fmol)":10.01,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0004,
            "Reads Examined":108293412,
            "Unpaired Reads":297134,
            "Initial Pool":"Pool-09602_F-09625_G-B1_1",
            "Unmapped":332424,
            "Pct. Duplic.":15.85,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"10.01 ng/uL",
            "Quant-it":"10.01 ng/uL",
            "Sum Reads":108293412,
            "Mean Tgt Cvg":207.54,
            "Sum MTC":207.54,
            "Pct. Zero Cvg":1.06,
            "Pct. Off Bait":14.36,
            "Pct. 10x":95.62,
            "Pct. 30x":91.05,
            "Pct. 100x":75.81
         },
         1:{
            "Run":"JAX_0327_AH772HBBXY",
            "QC Status":"Passed",
            "Sample":"TC2",
            "QC Record Id":5429281,
            "IGO Id":"09602_F_6",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":42.58,
            "Final Library Yield (fmol)":11.32,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0006,
            "Reads Examined":110724409,
            "Unpaired Reads":382347,
            "Initial Pool":"Pool-09602_F-09625_G-B1_1",
            "Unmapped":407769,
            "Pct. Duplic.":14.34,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"11.32 ng/uL",
            "Quant-it":"11.32 ng/uL",
            "Sum Reads":110724409,
            "Mean Tgt Cvg":210.5,
            "Sum MTC":210.5,
            "Pct. Zero Cvg":0.96,
            "Pct. Off Bait":15.27,
            "Pct. 10x":96.37,
            "Pct. 30x":91.1,
            "Pct. 100x":72.01
         },
         2:{
            "Run":"JAX_0327_AH772HBBXY",
            "QC Status":"Passed",
            "Sample":"TC2-Normal",
            "QC Record Id":5429313,
            "IGO Id":"09602_F_12",
            "Genome":"Human",
            "Tumor or Normal":"Normal",
            "Concentr.  (nM)":41.92,
            "Final Library Yield (fmol)":8.94,
            "Coverage Target":100,
            "Requested Reads (Millions)":60,
            "Pct. Adapters":0.0003,
            "Reads Examined":75647311,
            "Unpaired Reads":84590,
            "Initial Pool":"Pool-09602_F-09625_G-B1_1",
            "Unmapped":93854,
            "Pct. Duplic.":13.33,
            "Starting Amount":482.23611790000007,
            "Library Quality Control":"8.94 ng/uL",
            "Quant-it":"8.94 ng/uL",
            "Sum Reads":75647311,
            "Mean Tgt Cvg":144.42,
            "Sum MTC":144.42,
            "Pct. Zero Cvg":1.04,
            "Pct. Off Bait":13.94,
            "Pct. 10x":98.51,
            "Pct. 30x":97.85,
            "Pct. 100x":73.16
         },
         3:{
            "Run":"JAX_0327_AH772HBBXY",
            "QC Status":"Passed",
            "Sample":"P-0027584-N01-WES",
            "QC Record Id":5429363,
            "IGO Id":"09602_F_11",
            "Genome":"Human",
            "Tumor or Normal":"Normal",
            "Concentr.  (nM)":35.23,
            "Final Library Yield (fmol)":7.61,
            "Coverage Target":100,
            "Requested Reads (Millions)":60,
            "Pct. Adapters":0.0022,
            "Reads Examined":74465382,
            "Unpaired Reads":115963,
            "Initial Pool":"Pool-09602_F-09625_G-B1_1",
            "Unmapped":130774,
            "Pct. Duplic.":13.43,
            "Starting Amount":0.0,
            "Library Quality Control":"7.61 ng/uL",
            "Quant-it":"7.61 ng/uL",
            "Sum Reads":74465382,
            "Mean Tgt Cvg":140.18,
            "Sum MTC":140.18,
            "Pct. Zero Cvg":0.96,
            "Pct. Off Bait":13.87,
            "Pct. 10x":98.66,
            "Pct. 30x":98.27,
            "Pct. 100x":74.21
         },
         4:{
            "Run":"JAX_0327_AH772HBBXY",
            "QC Status":"Passed",
            "Sample":"P-0025908-N01-WES",
            "QC Record Id":5429379,
            "IGO Id":"09602_F_10",
            "Genome":"Human",
            "Tumor or Normal":"Normal",
            "Concentr.  (nM)":32.36,
            "Final Library Yield (fmol)":7.2,
            "Coverage Target":100,
            "Requested Reads (Millions)":60,
            "Pct. Adapters":0.0027,
            "Reads Examined":64289353,
            "Unpaired Reads":185878,
            "Initial Pool":"Pool-09602_F-09625_G-B1_1",
            "Unmapped":198572,
            "Pct. Duplic.":13.26,
            "Starting Amount":0.0,
            "Library Quality Control":"7.20 ng/uL",
            "Quant-it":"7.20 ng/uL",
            "Sum Reads":64289353,
            "Mean Tgt Cvg":121.33,
            "Sum MTC":121.33,
            "Pct. Zero Cvg":1.05,
            "Pct. Off Bait":13.27,
            "Pct. 10x":98.56,
            "Pct. 30x":98.14,
            "Pct. 100x":61.23
         },
         5:{
            "Run":"JAX_0327_AH772HBBXY",
            "QC Status":"Passed",
            "Sample":"TC5",
            "QC Record Id":5429381,
            "IGO Id":"09602_F_7",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":40.09,
            "Final Library Yield (fmol)":10.03,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0003,
            "Reads Examined":110683037,
            "Unpaired Reads":268536,
            "Initial Pool":"Pool-09602_F-09625_G-B1_1",
            "Unmapped":293476,
            "Pct. Duplic.":15.32,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"10.03 ng/uL",
            "Quant-it":"10.03 ng/uL",
            "Sum Reads":110683037,
            "Mean Tgt Cvg":211.87,
            "Sum MTC":211.87,
            "Pct. Zero Cvg":0.98,
            "Pct. Off Bait":13.86,
            "Pct. 10x":98.65,
            "Pct. 30x":98.09,
            "Pct. 100x":82.3
         },
         6:{
            "Run":"JAX_0327_AH772HBBXY",
            "QC Status":"Passed",
            "Sample":"P-0020849-N01-WES",
            "QC Record Id":5429403,
            "IGO Id":"09602_F_9",
            "Genome":"Human",
            "Tumor or Normal":"Normal",
            "Concentr.  (nM)":25.76,
            "Final Library Yield (fmol)":5.82,
            "Coverage Target":100,
            "Requested Reads (Millions)":60,
            "Pct. Adapters":0.0005,
            "Reads Examined":76002140,
            "Unpaired Reads":120965,
            "Initial Pool":"Pool-09602_F-09625_G-B1_1",
            "Unmapped":131323,
            "Pct. Duplic.":16.62,
            "Starting Amount":0.0,
            "Library Quality Control":"5.82 ng/uL",
            "Quant-it":"5.82 ng/uL",
            "Sum Reads":76002140,
            "Mean Tgt Cvg":139.8,
            "Sum MTC":139.8,
            "Pct. Zero Cvg":1.06,
            "Pct. Off Bait":12.96,
            "Pct. 10x":98.58,
            "Pct. 30x":98.27,
            "Pct. 100x":74.83
         },
         7:{
            "Run":"PITT_0369_BH77YLBBXY",
            "QC Status":"Repool-Sample",
            "Sample":"50741-TC1m1",
            "QC Record Id":5454412,
            "IGO Id":"09602_F_1",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":35.45,
            "Final Library Yield (fmol)":9.17,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0005,
            "Reads Examined":31888038,
            "Unpaired Reads":751199,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":1034139,
            "Pct. Duplic.":7.28,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"9.17 ng/uL",
            "Quant-it":"9.17 ng/uL",
            "Sum Reads":62223105,
            "Mean Tgt Cvg":66.94,
            "Sum MTC":131.03,
            "Pct. Zero Cvg":1.03,
            "Pct. Off Bait":15.08,
            "Pct. 10x":98.18,
            "Pct. 30x":84.62,
            "Pct. 100x":13.86
         },
         8:{
            "Run":"PITT_0369_BH77YLBBXY",
            "QC Status":"Repool-Sample",
            "Sample":"TC1",
            "QC Record Id":5454456,
            "IGO Id":"09602_F_5",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":40.72,
            "Final Library Yield (fmol)":10.67,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0002,
            "Reads Examined":34990855,
            "Unpaired Reads":92775,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":111328,
            "Pct. Duplic.":7.06,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"10.67 ng/uL",
            "Quant-it":"10.67 ng/uL",
            "Sum Reads":68318806,
            "Mean Tgt Cvg":74.87,
            "Sum MTC":146.37,
            "Pct. Zero Cvg":1.04,
            "Pct. Off Bait":13.43,
            "Pct. 10x":98.47,
            "Pct. 30x":90.34,
            "Pct. 100x":17.41
         },
         9:{
            "Run":"PITT_0369_BH77YLBBXY",
            "QC Status":"Repool-Sample",
            "Sample":"50825-TC6m1",
            "QC Record Id":5454474,
            "IGO Id":"09602_F_4",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":31.59,
            "Final Library Yield (fmol)":8.46,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0002,
            "Reads Examined":32992379,
            "Unpaired Reads":1276362,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":1748549,
            "Pct. Duplic.":8.34,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"8.46 ng/uL",
            "Quant-it":"8.46 ng/uL",
            "Sum Reads":64687234,
            "Mean Tgt Cvg":67.48,
            "Sum MTC":134.22,
            "Pct. Zero Cvg":0.98,
            "Pct. Off Bait":14.02,
            "Pct. 10x":98.15,
            "Pct. 30x":85.16,
            "Pct. 100x":14.17
         },
         10:{
            "Run":"PITT_0369_BH77YLBBXY",
            "QC Status":"Repool-Sample",
            "Sample":"50794-TC2m1",
            "QC Record Id":5454512,
            "IGO Id":"09602_F_2",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":21.09,
            "Final Library Yield (fmol)":5.72,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0006,
            "Reads Examined":29751091,
            "Unpaired Reads":5383521,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":7290994,
            "Pct. Duplic.":13.75,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"5.72 ng/uL",
            "Quant-it":"5.72 ng/uL",
            "Sum Reads":58462917,
            "Mean Tgt Cvg":63.86,
            "Sum MTC":125.9,
            "Pct. Zero Cvg":1.32,
            "Pct. Off Bait":12.98,
            "Pct. 10x":92.7,
            "Pct. 30x":72.51,
            "Pct. 100x":16.49
         },
         11:{
            "Run":"PITT_0369_BH77YLBBXY",
            "QC Status":"Repool-Sample",
            "Sample":"50824-TC5m1",
            "QC Record Id":5454522,
            "IGO Id":"09602_F_3",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":33.33,
            "Final Library Yield (fmol)":8.64,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0004,
            "Reads Examined":31211488,
            "Unpaired Reads":1515104,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":2027403,
            "Pct. Duplic.":8.8,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"8.64 ng/uL",
            "Quant-it":"8.64 ng/uL",
            "Sum Reads":61168144,
            "Mean Tgt Cvg":65.48,
            "Sum MTC":128.94,
            "Pct. Zero Cvg":1.01,
            "Pct. Off Bait":13.5,
            "Pct. 10x":98.34,
            "Pct. 30x":86.29,
            "Pct. 100x":12.9
         },
         12:{
            "Run":"PITT_0370_AH7GGKBBXY",
            "QC Status":"Repool-Sample",
            "Sample":"50741-TC1m1",
            "QC Record Id":5457745,
            "IGO Id":"09602_F_1",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":35.45,
            "Final Library Yield (fmol)":9.17,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0005,
            "Reads Examined":30335067,
            "Unpaired Reads":708836,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":973084,
            "Pct. Duplic.":7.38,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"9.17 ng/uL",
            "Quant-it":"9.17 ng/uL",
            "Sum Reads":62223105,
            "Mean Tgt Cvg":64.09,
            "Sum MTC":131.03,
            "Pct. Zero Cvg":1.04,
            "Pct. Off Bait":15.07,
            "Pct. 10x":98.09,
            "Pct. 30x":82.82,
            "Pct. 100x":12.17
         },
         13:{
            "Run":"PITT_0370_AH7GGKBBXY",
            "QC Status":"Repool-Sample",
            "Sample":"TC1",
            "QC Record Id":5457785,
            "IGO Id":"09602_F_5",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":40.72,
            "Final Library Yield (fmol)":10.67,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0002,
            "Reads Examined":33327951,
            "Unpaired Reads":76064,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":86394,
            "Pct. Duplic.":7.24,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"10.67 ng/uL",
            "Quant-it":"10.67 ng/uL",
            "Sum Reads":68318806,
            "Mean Tgt Cvg":71.5,
            "Sum MTC":146.37,
            "Pct. Zero Cvg":1.04,
            "Pct. Off Bait":13.41,
            "Pct. 10x":98.43,
            "Pct. 30x":88.93,
            "Pct. 100x":15.08
         },
         14:{
            "Run":"PITT_0370_AH7GGKBBXY",
            "QC Status":"Required-Additional-Reads",
            "Sample":"50825-TC6m1",
            "QC Record Id":5457805,
            "IGO Id":"09602_F_4",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":31.59,
            "Final Library Yield (fmol)":8.46,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0003,
            "Reads Examined":31694855,
            "Unpaired Reads":1198801,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":1626896,
            "Pct. Duplic.":8.46,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"8.46 ng/uL",
            "Quant-it":"8.46 ng/uL",
            "Sum Reads":64687234,
            "Mean Tgt Cvg":66.74,
            "Sum MTC":134.22,
            "Pct. Zero Cvg":0.99,
            "Pct. Off Bait":14.03,
            "Pct. 10x":98.13,
            "Pct. 30x":84.4,
            "Pct. 100x":13.87
         },
         15:{
            "Run":"PITT_0370_AH7GGKBBXY",
            "QC Status":"Required-Additional-Reads",
            "Sample":"50794-TC2m1",
            "QC Record Id":5457841,
            "IGO Id":"09602_F_2",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":21.09,
            "Final Library Yield (fmol)":5.72,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0004,
            "Reads Examined":28711826,
            "Unpaired Reads":5177529,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":6988225,
            "Pct. Duplic.":13.81,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"5.72 ng/uL",
            "Quant-it":"5.72 ng/uL",
            "Sum Reads":58462917,
            "Mean Tgt Cvg":62.03,
            "Sum MTC":125.9,
            "Pct. Zero Cvg":1.34,
            "Pct. Off Bait":12.97,
            "Pct. 10x":92.44,
            "Pct. 30x":71.38,
            "Pct. 100x":15.4
         },
         16:{
            "Run":"PITT_0370_AH7GGKBBXY",
            "QC Status":"Required-Additional-Reads",
            "Sample":"50824-TC5m1",
            "QC Record Id":5457849,
            "IGO Id":"09602_F_3",
            "Genome":"Human",
            "Tumor or Normal":"Tumor",
            "Concentr.  (nM)":33.33,
            "Final Library Yield (fmol)":8.64,
            "Coverage Target":150,
            "Requested Reads (Millions)":95,
            "Pct. Adapters":0.0003,
            "Reads Examined":29956656,
            "Unpaired Reads":1440322,
            "Initial Pool":"Pool-09483_E-09602_F-A1_1",
            "Unmapped":1913802,
            "Pct. Duplic.":9.01,
            "Starting Amount":250.00000000000003,
            "Library Quality Control":"8.64 ng/uL",
            "Quant-it":"8.64 ng/uL",
            "Sum Reads":61168144,
            "Mean Tgt Cvg":63.46,
            "Sum MTC":128.94,
            "Pct. Zero Cvg":1.02,
            "Pct. Off Bait":13.5,
            "Pct. 10x":98.31,
            "Pct. 30x":84.93,
            "Pct. 100x":11.84
         }
      },
      "style":{
         0:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         1:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         2:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-primary",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         3:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-primary",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         4:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-primary",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         5:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         6:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-primary",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         7:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         8:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         9:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         10:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         11:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         12:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         13:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         14:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         15:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         },
         16:{
            "Run":None,
            "QC Status":None,
            "Sample":None,
            "QC Record Id":None,
            "IGO Id":None,
            "Genome":None,
            "Tumor or Normal":"text-danger",
            "Concentr.  (nM)":None,
            "Final Library Yield (fmol)":None,
            "Coverage Target":None,
            "Requested Reads (Millions)":None,
            "Pct. Adapters":None,
            "Reads Examined":None,
            "Unpaired Reads":None,
            "Initial Pool":None,
            "Unmapped":None,
            "Pct. Duplic.":None,
            "Starting Amount":None,
            "Library Quality Control":None,
            "Quant-it":None,
            "Sum Reads":None,
            "Mean Tgt Cvg":None,
            "Sum MTC":None,
            "Pct. Zero Cvg":None,
            "Pct. Off Bait":None,
            "Pct. 10x":None,
            "Pct. 30x":None,
            "Pct. 100x":None
         }
      }
   },
   "chartsLinks":{

   },
   "projectType":{
      "recipe":"IDT_Exome_v1_FP",
      "startable":True,
      "quanted":True,
      "qcControlled":True,
      "table":"hs",
      "baitSet":"IDT_Exome_v1_FP_BAITS"
   },
   "columnOrder":[
      "QC Status",
      "Sample",
      "Mean Tgt Cvg",
      "Coverage Target",
      "Sum MTC",
      "Sum Reads",
      "Requested Reads (Millions)",
      "Reads Examined",
      "Unpaired Reads",
      "Unmapped",
      "Tumor or Normal",
      "Pct. Duplic.",
      "Pct. Off Bait",
      "Pct. Adapters",
      "Pct. Zero Cvg",
      "Pct. 10x",
      "Pct. 30x",
      "Pct. 100x"
   ]
}
